# Generated by Django 4.2.7 on 2023-11-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/card/avatar.png', upload_to='images/users'),
        ),
    ]
