# Generated by Django 4.2.7 on 2023-11-27 22:06

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/card/avatar.png', upload_to=user.models.upload_to),
        ),
    ]
