# Generated by Django 4.2.7 on 2023-11-17 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
        ('userinfo', '0002_remove_userinfo_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='own_card_link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='card.card'),
        ),
    ]
