# Generated by Django 4.2.7 on 2023-11-24 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images/card')),
                ('editors', models.ManyToManyField(related_name='editor_members', to=settings.AUTH_USER_MODEL)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(related_name='viewer_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
