# Generated by Django 4.2.7 on 2023-11-26 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card', '0005_alter_usercard_card_alter_usercard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editor_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='family',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewer_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
