# Generated by Django 4.2.7 on 2023-11-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_alter_card_editors_alter_card_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, default='images/card/avatar.png', upload_to='images/card'),
        ),
    ]
