# Generated by Django 4.2.7 on 2023-11-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_alter_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(default='images/card/avatar.png', upload_to='images/card'),
        ),
    ]
