# Generated by Django 4.2.7 on 2023-11-26 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card', '0008_alter_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscriber_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
