# Generated by Django 4.2.7 on 2023-11-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_publication_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/publication'),
        ),
    ]
